using AuditSphereOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace AuditSphereOps.Domain.Tests;

internal static class GeneralLedgerUploadSeed
{
    internal const string Csv = "PeriodCode,BookCode,Entity,Currency,JournalId,LineId,DocumentNumber,PostingDate,SourceSystem,SourceUser,AccountCode,Debit,Credit,OriginalCurrency,OriginalAmount,FunctionalAmount\nFY26,STAT,SYN-GL-CSV,QAR,J-1,L-1,D-1,2026-06-30,Synthetic,Source user,1000,100.123456,0,QAR,100.123456,100.123456\nFY26,STAT,SYN-GL-CSV,QAR,J-1,L-2,D-1,2026-06-30,Synthetic,Source user,3000,0,100.123456,QAR,-100.123456,-100.123456\n";
    internal sealed record Context(Guid PeriodId, Guid BookId, Guid ChartId);
    internal static async Task<Context> SeedAsync(AuditSphereDbContext db, PbcSeed.Fixture f) { var period = Guid.NewGuid(); var book = Guid.NewGuid(); var chart = Guid.NewGuid(); db.ClientReportingPeriods.Add(new() { Id = period, FirmId = f.FirmId, ClientId = f.ClientId, PeriodCode = "FY26", StartDate = new(2026, 1, 1), EndDate = new(2026, 12, 31), Currency = "QAR", Basis = "IFRS", CreatedByUserId = f.Staff.Id, CreatedAt = DateTimeOffset.UtcNow }); db.ClientReportingBooks.Add(new() { Id = book, FirmId = f.FirmId, ClientId = f.ClientId, PeriodId = period, Code = "STAT", InclusionRule = "STATUTORY_ONLY", Basis = "IFRS", Currency = "QAR", CreatedByUserId = f.Staff.Id, CreatedAt = DateTimeOffset.UtcNow }); db.ClientChartVersions.Add(new() { Id = chart, FirmId = f.FirmId, ClientId = f.ClientId, Version = 1, EffectiveFrom = new(2026, 1, 1), SourceScope = "Synthetic GL upload", CreatedByUserId = f.Staff.Id, CreatedAt = DateTimeOffset.UtcNow }); foreach (var code in new[] { "1000", "3000" }) db.ClientAccounts.Add(new() { Id = Guid.NewGuid(), FirmId = f.FirmId, ClientId = f.ClientId, ChartVersionId = chart, StableIdentity = code, AccountCode = code, AccountName = "Synthetic " + code, AccountType = "ASSET", NormalBalance = "DEBIT", CreatedAt = DateTimeOffset.UtcNow }); db.RoleGrants.Add(PbcSeed.Grant(f.FirmId, f.Staff, "AccountingPreparer", f.ClientId, f.EngagementId)); await db.SaveChangesAsync(); await db.ClientChartVersions.Where(x => x.Id == chart).ExecuteUpdateAsync(s => s.SetProperty(x => x.Status, "APPROVED").SetProperty(x => x.PublishedByUserId, f.Reviewer.Id).SetProperty(x => x.PublishedAt, DateTimeOffset.UtcNow)); return new(period, book, chart); }
}
