using System.Globalization;
using AuditSphereOps.Application.Abstractions;
using AuditSphereOps.Application.Operations;
using AuditSphereOps.Domain.Accounting;
using AuditSphereOps.Domain.Shared;
using Microsoft.EntityFrameworkCore;

namespace AuditSphereOps.Application.Accounting;

/// <summary>Scoped provenance for a native journal generated by a retained invoice submission.</summary>
public sealed record ClientOperationalInvoiceOrigin(Guid ClientId, Guid JournalId, Guid InvoiceId, Guid SubmissionId,
  string DraftRevision, string JournalSubmittedRevision);

public static partial class ClientOperationalLedgerWorkspace
{
  private static async Task<CommandResult> RequireManualJournalAsync(IClientAccountingDbContext db,
    Guid firmId, Guid clientId, Guid journalId, CancellationToken ct) =>
    await db.ClientSalesInvoiceSubmissions.AsNoTracking().AnyAsync(x => x.FirmId == firmId &&
      x.ClientId == clientId && x.JournalId == journalId, ct)
      ? CommandResult.Fail(ErrorCodes.ProtectedState, "This journal belongs to a client sales invoice. Use its invoice review and correction workflow.")
      : CommandResult.Ok();

  private static ClientOperationalInvoiceOrigin InvoiceOrigin(ClientSalesInvoiceSubmission submission) =>
    new(submission.ClientId, submission.JournalId, submission.InvoiceId, submission.Id,
      submission.DraftRevision.ToString(CultureInfo.InvariantCulture),
      submission.JournalSubmittedRevision.ToString(CultureInfo.InvariantCulture));

  private static async Task<ClientOperationalInvoiceOrigin?> InvoiceOriginAsync(IClientAccountingDbContext db,
    Guid firmId, Guid clientId, Guid journalId, CancellationToken ct, long? submittedRevision = null)
  {
    var query = db.ClientSalesInvoiceSubmissions.AsNoTracking().Where(x => x.FirmId == firmId &&
      x.ClientId == clientId && x.JournalId == journalId);
    if (submittedRevision.HasValue) query = query.Where(x => x.JournalSubmittedRevision == submittedRevision.Value);
    var submission = await query.OrderByDescending(x => x.JournalSubmittedRevision).FirstOrDefaultAsync(ct);
    return submission is null ? null : InvoiceOrigin(submission);
  }

  private static async Task<Dictionary<Guid, ClientOperationalInvoiceOrigin>> InvoiceOriginsAsync(IClientAccountingDbContext db,
    Guid firmId, Guid clientId, Guid[] journalIds, CancellationToken ct)
  {
    var submissions = await db.ClientSalesInvoiceSubmissions.AsNoTracking().Where(x => x.FirmId == firmId &&
      x.ClientId == clientId && journalIds.Contains(x.JournalId) &&
      !db.ClientSalesInvoiceSubmissions.Any(next => next.FirmId == x.FirmId && next.ClientId == x.ClientId &&
        next.JournalId == x.JournalId && next.JournalSubmittedRevision > x.JournalSubmittedRevision)).ToListAsync(ct);
    return submissions.ToDictionary(x => x.JournalId, InvoiceOrigin);
  }
}
