import { Component, DestroyRef, effect, inject, input, signal, untracked } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { Subscription, timeout } from 'rxjs';
import { SessionService } from '../../core/session';
import { guidPattern } from '../../core/contracts';
import { decodeCounterparties } from './counterparties-contract';
import { SalesInvoiceWorkflow, SalesInvoiceLifecycle } from './sales-invoice-workflow';

interface Period { id: string; code: string; status: string }
interface DraftLine { accountCode: string; description: string; quantity: string; unitPrice: string; discount: string }
interface Draft { id: string; invoiceId: string; clientId: string; periodId: string; revision: string; previousRevisionId: string | null; commandId: string; createdByUserId: string; snapshotHash: string; status: string; posted: boolean; issued: boolean;
  snapshot: { version: string; engineVersion: string; profileId: string; profileRevision: string; chartVersionId: string; draftReference: string; sourceReference: string; currency: string; documentDate: string; accountingDate: string; supplyDate: string; dueDate: string; evidenceReference: string; possibleDuplicateSourceReference: boolean;
    seller: { clientId: string; legalName: string }; customer: ReturnType<typeof decodeCounterparties>['counterparties'][number];
    policy: { currency: string; decimalPlaces: number; midpointRule: string; residualTreatment: string; maximumResidualMinorUnits: number; roundingAccountCode: string };
    lines: (DraftLine & { lineNumber: number; accountId: string; accountName: string; net: string; gross: string })[]; net: string; gross: string; taxTreatment: string } }
const amount = /^(?:0|[1-9]\d{0,12})(?:\.\d{1,6})?$/;
const date = /^\d{4}-\d{2}-\d{2}$/;
export function decodeSalesDraft(value: unknown, client: string, invoice?: string): Draft {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Invalid draft');
  const d = value as Draft;
  if (d.clientId !== client || (invoice && d.invoiceId !== invoice) || ![d.id, d.invoiceId, d.periodId, d.commandId, d.createdByUserId].every(x => typeof x === 'string' && guidPattern.test(x)) || typeof d.revision !== 'string' || !/^[1-9]\d{0,18}$/.test(d.revision) || d.status !== 'DRAFT' || d.posted !== false || d.issued !== false || !/^[a-f0-9]{64}$/.test(d.snapshotHash) || (d.previousRevisionId !== null && !guidPattern.test(d.previousRevisionId))) throw new Error('Invalid scoped draft');
  const s = d.snapshot, p = s?.policy;
  if (!s || ![s.profileId, s.chartVersionId].every(x => typeof x === 'string' && guidPattern.test(x)) || typeof s.profileRevision !== 'string' || !/^[1-9]\d{0,18}$/.test(s.profileRevision) || s.version !== 'client-sales-draft-v1' || s.engineVersion !== 'native-invoice-line-net-v1' || s.seller?.clientId !== client || !s.seller.legalName?.trim() ||
      !p || !Number.isInteger(p.decimalPlaces) || p.decimalPlaces < 0 || p.decimalPlaces > 6 || p.currency !== s.currency || !/^[A-Z]{3}$/.test(s.currency) || !['TO_EVEN', 'AWAY_FROM_ZERO'].includes(p.midpointRule) ||
      !['REJECT', 'EXPLICIT_ACCOUNT'].includes(p.residualTreatment) || !Number.isInteger(p.maximumResidualMinorUnits) || p.maximumResidualMinorUnits < 0 || p.maximumResidualMinorUnits > 3 || typeof p.roundingAccountCode !== 'string' ||
      (p.residualTreatment === 'REJECT' ? p.maximumResidualMinorUnits !== 0 || p.roundingAccountCode !== '' : p.maximumResidualMinorUnits < 1 || !p.roundingAccountCode.trim()) ||
      ![s.documentDate, s.accountingDate, s.supplyDate, s.dueDate].every(x => typeof x === 'string' && date.test(x)) || ![s.draftReference, s.sourceReference, s.evidenceReference].every(x => typeof x === 'string') || !s.draftReference.trim() || typeof s.possibleDuplicateSourceReference !== 'boolean' || s.taxTreatment !== 'NONE' || !Array.isArray(s.lines) || s.lines.length < 1 || s.lines.length > 100) throw new Error('Invalid retained invoice details');
  decodeCounterparties({ clientId: client, role: 'CUSTOMER', page: 0, pageSize: 25, total: 1, bookkeepingActive: true, counterparties: [s.customer] }, client, 'CUSTOMER', 0);
  const money = new RegExp(`^(?:0|[1-9]\\d{0,12})${p.decimalPlaces ? `\\.\\d{${p.decimalPlaces}}` : ''}$`);
  if (![s.net, s.gross].every(x => typeof x === 'string' && money.test(x)) || s.net !== s.gross) throw new Error('Invalid exact invoice totals');
  s.lines.forEach((l, i) => { if (l.lineNumber !== i + 1 || !guidPattern.test(l.accountId) || ![l.accountCode, l.accountName, l.description].every(x => typeof x === 'string' && x.trim()) || ![l.quantity, l.unitPrice, l.discount].every(x => typeof x === 'string' && amount.test(x)) || ![l.net, l.gross].every(x => typeof x === 'string' && money.test(x)) || l.net !== l.gross) throw new Error('Invalid retained invoice line'); });
  const minor = (v: string) => BigInt(v.replace('.', ''));
  if (s.lines.reduce((sum, l) => sum + minor(l.net), 0n) !== minor(s.net) || s.lines.some(l => BigInt(l.quantity.replace('.', '')) === 0n)) throw new Error('Invalid exact draft controls');
  return d;
}
@Component({ selector: 'audit-sales-invoice-drafts', imports: [FormsModule, MatButtonModule, SalesInvoiceWorkflow], template: `<section aria-label="Client sales invoice preparation">
  <h3>Client sales invoice drafts</h3><p>Saving a draft preserves preparation details. It does not post revenue or receivables, issue an invoice or send a document.</p>
  @if (error()) { <p role="alert">{{ error() }}</p> }
  @if (pending()) { <p role="status">This exact draft request is unconfirmed. Its fields remain locked until recovery or an explicit retry of the same request.</p><button matButton type="button" [disabled]="busy()" (click)="recover()">Recover invoice draft request</button>
    @if (retry()) { <label><input type="checkbox" [ngModel]="reviewed()" (ngModelChange)="reviewed.set($event)" /> Retry this exact unchanged draft request.</label><button matButton type="button" [disabled]="busy() || !reviewed()" (click)="sendPending()">Retry original invoice draft request</button> }
  }
  <details><summary>Prepare or revise a sales draft</summary>
    <label>Customer page</label><button matButton type="button" [disabled]="busy()" (click)="loadCustomers(0)">Load client customers</button>
    @if (customers(); as c) { <p>{{ c.total }} customers · Page {{ c.page + 1 }}</p><button matButton type="button" [disabled]="busy() || c.page === 0" (click)="loadCustomers(c.page - 1)">Previous invoice customers</button><button matButton type="button" [disabled]="busy() || (c.page + 1) * 25 >= c.total" (click)="loadCustomers(c.page + 1)">Next invoice customers</button> }
    <form #form="ngForm" (ngSubmit)="form.valid && save()"><fieldset [disabled]="busy() || !!pending()"><legend>Unposted sales draft</legend>
      <label>Sales draft period <select aria-label="Sales draft period" name="period" [(ngModel)]="periodId" (ngModelChange)="reviewed.set(false)" required><option value="">Choose period</option>@for (p of periods(); track p.id) { <option [value]="p.id" [disabled]="p.status === 'CLOSED'">{{ p.code }}</option> }</select></label>
      <label>Sales draft customer <select aria-label="Sales draft customer" name="customer" [(ngModel)]="customerId" (ngModelChange)="reviewed.set(false)" required><option value="">Choose customer</option>@for (c of customers()?.counterparties || []; track c.id) { <option [value]="c.id">{{ c.displayName }} · {{ c.legalName }}</option> }</select></label>
      <label>Internal sales draft reference <input name="reference" [(ngModel)]="draftReference" (ngModelChange)="reviewed.set(false)" [readonly]="!!invoiceId" required maxlength="100" /></label>
      <label>Client sales source reference <input name="source" [(ngModel)]="sourceReference" (ngModelChange)="reviewed.set(false)" maxlength="200" /></label>
      <label>Sales document date <input type="date" name="documentDate" [(ngModel)]="documentDate" (ngModelChange)="reviewed.set(false)" required /></label>
      <label>Sales accounting date <input type="date" name="accountingDate" [(ngModel)]="accountingDate" (ngModelChange)="reviewed.set(false)" required /></label>
      <label>Sales supply date <input type="date" name="supplyDate" [(ngModel)]="supplyDate" (ngModelChange)="reviewed.set(false)" required /></label>
      <label>Sales due date <input type="date" name="dueDate" [(ngModel)]="dueDate" (ngModelChange)="reviewed.set(false)" required /></label>
      <p>Book currency: {{ currency() }} · Tax treatment: no tax components</p>
      <label>Draft currency precision <select aria-label="Draft currency precision" name="precision" [(ngModel)]="precision" (ngModelChange)="reviewed.set(false)" required><option value="">Declare precision</option>@for (n of [0,1,2,3,4,5,6]; track n) { <option [value]="'' + n">{{ n }} decimal places</option> }</select></label>
      <label>Draft midpoint rounding <select aria-label="Draft midpoint rounding" name="midpoint" [(ngModel)]="midpoint" (ngModelChange)="reviewed.set(false)" required><option value="">Declare rounding</option><option value="TO_EVEN">To even</option><option value="AWAY_FROM_ZERO">Away from zero</option></select></label>
      @for (l of lines; track $index; let i = $index) { <fieldset><legend>Sales line {{ i + 1 }}</legend><label>Sales income account <input [name]="'account' + i" [(ngModel)]="l.accountCode" (ngModelChange)="reviewed.set(false)" required maxlength="100" /></label><label>Sales line description <input [name]="'description' + i" [(ngModel)]="l.description" (ngModelChange)="reviewed.set(false)" required maxlength="2000" /></label><label>Sales quantity <input [name]="'quantity' + i" [(ngModel)]="l.quantity" (ngModelChange)="reviewed.set(false)" required pattern="(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?" /></label><label>Sales unit price <input [name]="'price' + i" [(ngModel)]="l.unitPrice" (ngModelChange)="reviewed.set(false)" required pattern="(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?" /></label><label>Sales line discount <input [name]="'discount' + i" [(ngModel)]="l.discount" (ngModelChange)="reviewed.set(false)" required pattern="(?:0|[1-9][0-9]{0,12})(?:\\.[0-9]{1,6})?" /></label><button matButton type="button" [disabled]="lines.length === 1" (click)="lines.splice(i,1); reviewed.set(false)">Remove sales line</button></fieldset> }
      <button matButton type="button" [disabled]="lines.length >= 100" (click)="addLine()">Add sales line</button>
      <label>Sales evidence reference <input name="evidence" [(ngModel)]="evidenceReference" (ngModelChange)="reviewed.set(false)" maxlength="2000" /></label>
      <label><input type="checkbox" name="reviewed" [ngModel]="reviewed()" (ngModelChange)="reviewed.set($event)" /> I checked the client, customer, dates, declared calculation policy and exact draft lines.</label>
      <button matButton type="submit" [disabled]="form.invalid || !reviewed() || busy() || !!pending()">Save client sales draft</button>
    </fieldset></form><button matButton type="button" [disabled]="busy() || !!pending()" (click)="reset()">Start a separate sales draft</button>
  </details>
  <label>Open client sales draft by ID <input [(ngModel)]="openId" /></label><button matButton type="button" [disabled]="busy() || !!pending() || !validId(openId)" (click)="open()">Open client sales draft</button>
  @if (saved(); as d) { <section aria-label="Saved client sales draft"><h4>{{ d.snapshot.draftReference }} · Preparation revision {{ d.revision }}</h4><p>Seller: {{ d.snapshot.seller.legalName }} · Customer: {{ d.snapshot.customer.legalName }}</p><p>Captured customer address: {{ d.snapshot.customer.address }}</p><p>Sales draft ID: {{ d.invoiceId }} · Request: {{ d.commandId }}</p>@if (d.snapshot.possibleDuplicateSourceReference) { <p role="alert">Another sales draft in this client book uses this source reference. Review the source before submission.</p> }<p>Preserved preparation gross: {{ d.snapshot.gross }} {{ d.snapshot.currency }}</p><table><caption>Preserved sales draft lines</caption><thead><tr><th>Account</th><th>Description</th><th>Quantity</th><th>Unit price</th><th>Discount</th><th>Net</th></tr></thead><tbody>@for (l of d.snapshot.lines; track l.lineNumber) { <tr><td>{{ l.accountCode }}</td><td>{{ l.description }}</td><td>{{ l.quantity }}</td><td>{{ l.unitPrice }}</td><td>{{ l.discount }}</td><td>{{ l.net }}</td></tr> }</tbody></table><button matButton type="button" [disabled]="busy() || !!pending() || !canEdit(d)" (click)="edit(d)">Revise saved sales draft</button><p>This immutable preparation snapshot does not describe the current invoice posting state. Inspect the lifecycle below.</p><audit-sales-invoice-workflow [clientId]="clientId()" [invoiceId]="d.invoiceId" [preparationRevision]="d.revision" (lifecycleChange)="lifecycle.set($event)" /></section> }
</section>` })
export class SalesInvoiceDrafts {
  readonly clientId = input.required<string>(); readonly currency = input.required<string>(); readonly periods = input.required<Period[]>();
  private readonly http = inject(HttpClient); private readonly session = inject(SessionService);
  readonly saved = signal<Draft | null>(null); readonly lifecycle = signal<SalesInvoiceLifecycle | null>(null); readonly customers = signal<ReturnType<typeof decodeCounterparties> | null>(null); readonly busy = signal(false); readonly error = signal(''); readonly reviewed = signal(false); readonly retry = signal(false);
  readonly pending = signal<{ client: string; actor: string; body: Record<string, unknown> } | null>(null); readonly validId = (v: string) => guidPattern.test(v); readonly userId = () => this.session.current()?.userId ?? '';
  invoiceId: string | null = null; expectedRevision = '0'; draftReference = ''; sourceReference = ''; periodId = ''; customerId = ''; documentDate = ''; accountingDate = ''; supplyDate = ''; dueDate = ''; precision = ''; midpoint = ''; evidenceReference = ''; openId = ''; lines: DraftLine[] = [];
  private request = 0; private operation?: Subscription;
  private readonly invalidate = effect(() => { this.clientId(); this.session.invalidation(); untracked(() => { this.operation?.unsubscribe(); ++this.request; this.busy.set(false); this.saved.set(null); this.lifecycle.set(null); this.customers.set(null); this.pending.set(null); this.error.set(''); this.openId = ''; this.reset(); }); });
  private readonly policyInvalidation = effect(() => { this.currency(); this.periods(); untracked(() => this.reviewed.set(false)); });
  constructor() { inject(DestroyRef).onDestroy(() => this.operation?.unsubscribe()); }
  reset(): void { this.invoiceId = null; this.expectedRevision = '0'; this.draftReference = ''; this.sourceReference = ''; this.periodId = ''; this.customerId = ''; this.documentDate = ''; this.accountingDate = ''; this.supplyDate = ''; this.dueDate = ''; this.precision = ''; this.midpoint = ''; this.evidenceReference = ''; this.lines = []; this.addLine(); this.retry.set(false); this.reviewed.set(false); }
  addLine(): void { this.lines.push({ accountCode: '', description: '', quantity: '1', unitPrice: '0', discount: '0' }); this.reviewed.set(false); }
  loadCustomers(page: number): void {
    if (this.busy()) return; const client = this.clientId(), generation = this.session.invalidation(), request = ++this.request; this.busy.set(true); this.customers.set(null);
    this.operation = this.http.get<unknown>(`/api/ui/accounting/clients/${client}/counterparties`, { params: { role: 'CUSTOMER', page: String(page), pageSize: '25' } }).pipe(timeout(15000)).subscribe({ next: v => { if (request !== this.request || generation !== this.session.invalidation() || client !== this.clientId()) return; this.busy.set(false); try { this.customers.set(decodeCounterparties(v, client, 'CUSTOMER', page)); } catch { this.error.set('Customer list could not be validated.'); } }, error: e => this.failure(e, request, generation, 'Customers unavailable.') });
  }
  save(): void {
    if (this.busy() || this.pending() || !this.reviewed() || !this.validId(this.periodId) || !this.validId(this.customerId) || !/^[0-6]$/.test(this.precision) || !['TO_EVEN', 'AWAY_FROM_ZERO'].includes(this.midpoint) || this.lines.length < 1 || this.lines.length > 100 || this.lines.some(l => !amount.test(l.quantity) || !amount.test(l.unitPrice) || !amount.test(l.discount))) return;
    this.pending.set({ client: this.clientId(), actor: this.userId(), body: { commandId: crypto.randomUUID(), invoiceId: this.invoiceId, expectedRevision: this.expectedRevision, draftReference: this.draftReference.trim(), sourceReference: this.sourceReference.trim(), periodId: this.periodId, customerId: this.customerId, documentDate: this.documentDate, accountingDate: this.accountingDate, supplyDate: this.supplyDate, dueDate: this.dueDate, currency: this.currency(), policy: { currency: this.currency(), decimalPlaces: Number(this.precision), midpointRule: this.midpoint, residualTreatment: 'REJECT', maximumResidualMinorUnits: 0, roundingAccountCode: '' }, lines: this.lines.map(l => ({ ...l, accountCode: l.accountCode.trim(), description: l.description.trim() })), evidenceReference: this.evidenceReference.trim(), reviewed: true } }); this.sendPending(true);
  }
  sendPending(initial = false): void {
    const p = this.pending(); if (!p || this.busy() || p.client !== this.clientId() || p.actor !== this.userId() || (!initial && (!this.retry() || !this.reviewed()))) return;
    const generation = this.session.invalidation(), request = ++this.request; this.busy.set(true); this.reviewed.set(false); this.retry.set(false); this.error.set('');
    this.operation = this.http.post<unknown>(`/api/ui/accounting/clients/${p.client}/sales-invoice-drafts`, p.body).pipe(timeout(15000)).subscribe({ next: v => this.accept(v, p, request, generation), error: e => { if (request !== this.request || generation !== this.session.invalidation()) return; this.busy.set(false); if (e.status === 400 || e.status === 403) { this.pending.set(null); this.error.set('Draft refused. Check current service, revision, customer, period, declared policy and income accounts.'); } else this.error.set('Draft outcome unconfirmed. Recover this exact request.'); if (e.status === 401) this.session.clear(); } });
  }
  recover(): void {
    const p = this.pending(); if (!p || this.busy() || p.client !== this.clientId() || p.actor !== this.userId()) return; const generation = this.session.invalidation(), request = ++this.request; this.busy.set(true); this.reviewed.set(false); this.retry.set(false);
    this.operation = this.http.get<unknown>(`/api/ui/accounting/clients/${p.client}/sales-invoice-draft-requests/${p.body['commandId']}`).pipe(timeout(15000)).subscribe({ next: v => this.accept(v, p, request, generation), error: e => { if (request !== this.request || generation !== this.session.invalidation()) return; this.busy.set(false); if (e.status === 404) { this.retry.set(true); this.error.set('No saved outcome was found. Explicitly retry this unchanged request if appropriate.'); } else this.error.set('Recovery unavailable; retain the exact request.'); if (e.status === 401) this.session.clear(); } });
  }
  private accept(v: unknown, p: { client: string; actor: string; body: Record<string, unknown> }, request: number, generation: number): void { if (request !== this.request || generation !== this.session.invalidation() || p.client !== this.clientId()) return; this.busy.set(false); try { const d = decodeSalesDraft(v, p.client); if (d.commandId !== p.body['commandId'] || d.createdByUserId !== p.actor) throw new Error('Wrong request'); this.saved.set(d); this.openId = d.invoiceId; this.pending.set(null); this.reset(); } catch { this.error.set('Draft response did not match this exact request. Recover before another save.'); } }
  open(): void { if (this.busy() || this.pending() || !this.validId(this.openId)) return; const client = this.clientId(), invoice = this.openId, generation = this.session.invalidation(), request = ++this.request; this.busy.set(true); this.saved.set(null); this.operation = this.http.get<unknown>(`/api/ui/accounting/clients/${client}/sales-invoice-drafts/${invoice}`).pipe(timeout(15000)).subscribe({ next: v => { if (request !== this.request || generation !== this.session.invalidation()) return; this.busy.set(false); try { this.saved.set(decodeSalesDraft(v, client, invoice)); } catch { this.error.set('Saved draft response could not be validated.'); } }, error: e => this.failure(e, request, generation, 'Saved draft unavailable.') }); }
  canEdit(d: Draft): boolean { const w = this.lifecycle(); return !!w?.canRevise && w.clientId === this.clientId() && w.invoiceId === d.invoiceId && w.draftRevision === d.revision && d.createdByUserId === this.userId(); }
  edit(d: Draft): void { if (this.busy() || this.pending() || !this.canEdit(d)) return; const s = d.snapshot; this.invoiceId = d.invoiceId; this.expectedRevision = d.revision; this.draftReference = s.draftReference; this.sourceReference = s.sourceReference; this.periodId = d.periodId; this.customerId = s.customer.id; this.documentDate = s.documentDate; this.accountingDate = s.accountingDate; this.supplyDate = s.supplyDate; this.dueDate = s.dueDate; this.precision = String(s.policy.decimalPlaces); this.midpoint = s.policy.midpointRule; this.evidenceReference = s.evidenceReference; this.lines = s.lines.map(l => ({ accountCode: l.accountCode, description: l.description, quantity: l.quantity, unitPrice: l.unitPrice, discount: l.discount })); this.reviewed.set(false); }
  private failure(e: { status: number }, request: number, generation: number, message: string): void { if (request !== this.request || generation !== this.session.invalidation()) return; this.busy.set(false); this.error.set(message); if (e.status === 401) this.session.clear(); }
}
