using System.Data.Common;
using System.Net;
using System.Text;
using System.Text.Json;
using AuditSphereOps.Application.Accounting;
using AuditSphereOps.Domain.Security;
using AuditSphereOps.Domain.Shared;
using AuditSphereOps.Domain.Tests;
using AuditSphereOps.Infrastructure.Persistence;
using AuditSphereOps.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
namespace AuditSphereOps.Api.Tests;

public sealed class GeneralLedgerUploadApiTests
{
    [Fact] public async Task ExactReviewedConcurrentUploadRetainsOneSourceAndReconcilesWithoutMutatingSelection() { await using var pg = await OwnedPostgresDatabase.CreateAsync("API-GL-UPLOAD"); var f = await PbcSeed.SeedAsync(pg); await using (var db = new AuditSphereDbContext(pg.Options)) await GeneralLedgerUploadSeed.SeedAsync(db, f); using var factory = Factory(pg, f.Staff); using var c = factory.CreateClient(new() { AllowAutoRedirect = false }); var csrf = await SignIn(c); var root = Root(f); Assert.Equal(HttpStatusCode.Forbidden, (await Upload(c, "wrong", root + "/preview")).StatusCode); var p = await Json(await Upload(c, csrf, root + "/preview")); Assert.True(p.GetProperty("canImport").GetBoolean()); Assert.Equal("100.123456", p.GetProperty("debit").GetString()); Assert.Equal(HttpStatusCode.Conflict, (await Upload(c, csrf, root + "/import", p, reviewed: false)).StatusCode); var writes = await Task.WhenAll(Upload(c, csrf, root + "/import", p), Upload(c, csrf, root + "/import", p)); var receipts = await Task.WhenAll(writes.Select(Json)); Assert.All(receipts, r => Assert.Equal("SEALED", r.GetProperty("importState").GetString())); var id = receipts[0].GetProperty("importBatchId").GetGuid(); Assert.Equal(id, receipts[1].GetProperty("importBatchId").GetGuid()); Assert.Equal(id, (await Json(await Upload(c, csrf, root + "/reconcile"))).GetProperty("importBatchId").GetGuid()); Assert.Equal(id, (await Json(await Upload(c, csrf, root + "/import", p))).GetProperty("importBatchId").GetGuid()); await using var proof = new AuditSphereDbContext(pg.Options); Assert.Single(await proof.SourceImportBatches.ToListAsync()); Assert.Equal(2, await proof.GeneralLedgerLines.CountAsync()); Assert.Empty(await proof.SourceAcceptanceDecisions.ToListAsync()); Assert.Empty(await proof.GeneralLedgerCompletenessBridges.ToListAsync()); Assert.Equal(1, await proof.ClientSafetyStates.Where(x => x.Id == f.ClientId).Select(x => x.InputGeneration).SingleAsync()); }
    [Fact] public async Task MalformedUnbalancedUnknownAccountsDatesAndDimensionsPublishNothing() { await using var pg = await OwnedPostgresDatabase.CreateAsync("API-GL-UPLOAD-INVALID"); var f = await PbcSeed.SeedAsync(pg); await using (var db = new AuditSphereDbContext(pg.Options)) await GeneralLedgerUploadSeed.SeedAsync(db, f); using var factory = Factory(pg, f.Staff); using var c = factory.CreateClient(new() { AllowAutoRedirect = false }); var csrf = await SignIn(c); var texts = new[] { GeneralLedgerUploadSeed.Csv.Replace(",3000,", ",UNKNOWN,"), GeneralLedgerUploadSeed.Csv.Replace("-100.123456,-100.123456", "-100.123455,-100.123455"), GeneralLedgerUploadSeed.Csv.Replace("2026-06-30", "2027-06-30"), GeneralLedgerUploadSeed.Csv.Replace("100.123456", "1e2"), GeneralLedgerUploadSeed.Csv + "\"unterminated", GeneralLedgerUploadSeed.Csv.Replace("PeriodCode", "Unknown"), GeneralLedgerUploadSeed.Csv.Replace("L-2", "L-1") }; foreach (var text in texts) Assert.Equal(HttpStatusCode.BadRequest, (await Upload(c, csrf, Root(f) + "/preview", text: text)).StatusCode); var p = await Json(await Upload(c, csrf, Root(f) + "/preview")); Assert.Equal(HttpStatusCode.Conflict, (await Upload(c, csrf, Root(f) + "/import", p, text: GeneralLedgerUploadSeed.Csv.Replace("Source user", "Different user"))).StatusCode); Assert.Equal(HttpStatusCode.BadRequest, (await Upload(c, csrf, Root(f) + "/preview", text: GeneralLedgerUploadSeed.Csv, name: "source.xlsx")).StatusCode); await using var db2 = new AuditSphereDbContext(pg.Options); Assert.Empty(await db2.SourceImportBatches.ToListAsync()); }
    [Fact] public async Task ScopeBookStatusStaleContextAndEpochDenyWithoutHiddenReceipts() { await using var pg = await OwnedPostgresDatabase.CreateAsync("API-GL-UPLOAD-SCOPE"); var f = await PbcSeed.SeedAsync(pg); var other = await PbcSeed.SeedAsync(pg); GeneralLedgerUploadSeed.Context context; await using (var db = new AuditSphereDbContext(pg.Options)) { context = await GeneralLedgerUploadSeed.SeedAsync(db, f); await GeneralLedgerUploadSeed.SeedAsync(db, other); } using var factory = Factory(pg, f.Staff); using var c = factory.CreateClient(new() { AllowAutoRedirect = false }); var csrf = await SignIn(c); foreach (var id in new[] { other.EngagementId, Guid.NewGuid() }) foreach (var action in new[] { "preview", "import", "reconcile" }) Assert.Equal(HttpStatusCode.Forbidden, (await Upload(c, csrf, $"/api/ui/engagements/{id}/general-ledger/{action}")).StatusCode); using var cf = Factory(pg, f.Client); using var client = cf.CreateClient(new() { AllowAutoRedirect = false }); var cc = await SignIn(client); Assert.Equal(HttpStatusCode.Forbidden, (await Upload(client, cc, Root(f) + "/preview")).StatusCode); var p = await Json(await Upload(c, csrf, Root(f) + "/preview")); await using (var db = new AuditSphereDbContext(pg.Options)) await db.ClientSafetyStates.Where(x => x.Id == f.ClientId).ExecuteUpdateAsync(s => s.SetProperty(x => x.InputGeneration, x => x.InputGeneration + 1)); Assert.Equal(HttpStatusCode.Conflict, (await Upload(c, csrf, Root(f) + "/import", p)).StatusCode); p = await Json(await Upload(c, csrf, Root(f) + "/preview")); await using (var db = new AuditSphereDbContext(pg.Options)) await db.ClientReportingBooks.Where(x => x.Id == context.BookId).ExecuteUpdateAsync(s => s.SetProperty(x => x.Status, "CLOSED")); var blocked = await Json(await Upload(c, csrf, Root(f) + "/preview")); Assert.False(blocked.GetProperty("canImport").GetBoolean()); Assert.Equal(HttpStatusCode.BadRequest, (await Upload(c, csrf, Root(f) + "/import", p)).StatusCode); await using (var db = new AuditSphereDbContext(pg.Options)) await db.Users.Where(x => x.Id == f.Staff.Id).ExecuteUpdateAsync(s => s.SetProperty(x => x.SessionEpoch, x => x.SessionEpoch + 1)); Assert.Equal(HttpStatusCode.Unauthorized, (await Upload(c, csrf, Root(f) + "/reconcile")).StatusCode); await using var proof = new AuditSphereDbContext(pg.Options); Assert.Empty(await proof.SourceImportBatches.ToListAsync()); }
    [Fact] public async Task EpochRevokedAfterSourceSaveRollsBackAllRows() { await using var pg = await OwnedPostgresDatabase.CreateAsync("API-GL-UPLOAD-LATE"); var f = await PbcSeed.SeedAsync(pg); await using (var db = new AuditSphereDbContext(pg.Options)) await GeneralLedgerUploadSeed.SeedAsync(db, f); var actor = PbcSeed.Actor(f.Staff, "AccountingPreparer"); var interceptor = new LateEpoch(async () => { await using var db = new AuditSphereDbContext(pg.Options); await db.Users.Where(x => x.Id == f.Staff.Id).ExecuteUpdateAsync(s => s.SetProperty(x => x.SessionEpoch, x => x.SessionEpoch + 1)); }); await using (var db = new AuditSphereDbContext(new DbContextOptionsBuilder<AuditSphereDbContext>(pg.Options).AddInterceptors(interceptor).Options)) { var bytes = Encoding.UTF8.GetBytes(GeneralLedgerUploadSeed.Csv); var p = await GeneralLedgerUploadWorkspace.PreviewAsync(db, actor, f.EngagementId, "source.csv", bytes); Assert.True(p.Succeeded, p.Message); var r = await GeneralLedgerUploadWorkspace.ImportAsync(db, actor, f.EngagementId, "source.csv", bytes, p.Value!.Revision, p.Value.FileSha256, true); Assert.Equal(ErrorCodes.GenerationStale, r.ErrorCode); } await using var proof = new AuditSphereDbContext(pg.Options); Assert.Empty(await proof.SourceImportBatches.ToListAsync()); Assert.Empty(await proof.GeneralLedgerLines.ToListAsync()); }
    private sealed class LateEpoch(Func<Task> change) : DbCommandInterceptor { private bool done; public override async ValueTask<DbDataReader> ReaderExecutedAsync(DbCommand c, CommandExecutedEventData e, DbDataReader r, CancellationToken ct = default) { if (!done && c.CommandText.Contains("INSERT INTO source_import_batches", StringComparison.Ordinal)) { done = true; await change(); } return r; } }
    private static string Root(PbcSeed.Fixture f) => $"/api/ui/engagements/{f.EngagementId}/general-ledger";
    private static StandaloneApiApplicationFactory Factory(OwnedPostgresDatabase pg, AppUser u) => new(new Dictionary<string, string?> { ["ConnectionStrings:AuditSphere"] = pg.ConnectionString, ["DevelopmentIdentity:Enabled"] = "true", ["DevelopmentIdentity:TenantId"] = u.TenantId, ["DevelopmentIdentity:Subject"] = u.Subject, ["Application:AllowSimulationAdapters"] = "true", ["ExternalEffects:Enabled"] = "false" });
    private static async Task<string> SignIn(HttpClient c) { await c.GetAsync("/auth/sign-in"); using var r = await c.GetAsync("/api/ui/session"); return Uri.UnescapeDataString(r.Headers.GetValues("Set-Cookie").Single(x => x.StartsWith("XSRF-TOKEN=", StringComparison.Ordinal)).Split(';')[0]["XSRF-TOKEN=".Length..]); }
    private static async Task<JsonElement> Json(HttpResponseMessage r) { Assert.Equal(HttpStatusCode.OK, r.StatusCode); using var doc = JsonDocument.Parse(await r.Content.ReadAsStringAsync()); return doc.RootElement.TryGetProperty("value", out var v) ? v.Clone() : doc.RootElement.Clone(); }
    private static Task<HttpResponseMessage> Upload(HttpClient c, string csrf, string url, JsonElement? review = null, bool reviewed = true, string text = GeneralLedgerUploadSeed.Csv, string name = "source.csv") { var form = new MultipartFormDataContent(); form.Add(new ByteArrayContent(Encoding.UTF8.GetBytes(text)), "file", name); if (review is { } p) { form.Add(new StringContent(p.GetProperty("revision").GetString()!), "revision"); form.Add(new StringContent(p.GetProperty("fileSha256").GetString()!), "fileSha256"); form.Add(new StringContent(reviewed ? "true" : "false"), "reviewed"); } var request = new HttpRequestMessage(HttpMethod.Post, url) { Content = form }; request.Headers.Add("X-XSRF-TOKEN", csrf); return c.SendAsync(request); }
}
