using AuditSphereOps.Domain.Tests;
using Microsoft.EntityFrameworkCore;
using Microsoft.Playwright;

namespace AuditSphereOps.E2E.Tests;
public sealed class AngularGeneralLedgerCompletenessJourneyTests
{
  [Fact]
  [Trait("CaseId","ANGULAR-GL-COMPLETENESS")]
  public async Task NativePreparation_LostResponseReload_DurableWorker_IndependentApprovalAndRevocation()
  {
    await using var host=await OwnedHost.StartAsync(startWorker:false,caseId:"ANGULAR-GL-COMPLETENESS");var p=await Seed(host);
    var origin=await host.StartApiForIdentityAsync(host.Fixture.Staff,new Dictionary<string,string>{["AngularUi__Enabled"]="true"});
    using var pw=await Playwright.CreateAsync();await using var browser=await PlaywrightBrowser.LaunchAsync(pw);var page=await browser.NewPageAsync();var errors=new List<string>();page.PageError+=(_,e)=>errors.Add(e);
    await page.GotoAsync(origin+"/auth/sign-in?returnUrl="+Uri.EscapeDataString($"/ui/app/engagements/{host.Fixture.EngagementId}/general-ledger"));
    await page.GetByRole(AriaRole.Button,new(){Name=$"Inspect ledger {p.BatchId:D}",Exact=true}).ClickAsync();await page.GetByRole(AriaRole.Link,new(){Name="Prepare and review GL completeness",Exact=true}).ClickAsync();
    await page.GetByLabel("Closing trial balance",new(){Exact=true}).SelectOptionAsync(p.ClosingId.ToString("D"));await page.GetByLabel("Opening trial balance",new(){Exact=true}).SelectOptionAsync(p.OpeningId.ToString("D"));await page.GetByRole(AriaRole.Button,new(){Name="Review completeness source pair",Exact=true}).ClickAsync();
    await page.GetByLabel("Completeness evidence reference",new(){Exact=true}).FillAsync("Synthetic browser completeness evidence");await page.GetByLabel(Assent,new(){Exact=true}).CheckAsync();
    var writes=0;await page.RouteAsync($"**/gl-sources/{p.BatchId}/completeness",async r=>{if(r.Request.Method!="POST"){await r.ContinueAsync();return;}writes++;var response=await r.FetchAsync();Assert.Equal(200,response.Status);await r.AbortAsync("failed");});
    await page.GetByRole(AriaRole.Button,new(){Name="Prepare reviewed completeness",Exact=true}).ClickAsync();await Assertions.Expect(page.GetByRole(AriaRole.Heading,new(){Name="Completeness outcome needs review",Exact=true})).ToBeVisibleAsync();await page.ReloadAsync();await page.GetByRole(AriaRole.Button,new(){Name="Read persisted completeness",Exact=true}).ClickAsync();await page.GetByRole(AriaRole.Button,new(){Name="I reviewed the persisted completeness",Exact=true}).ClickAsync();
    Assert.Equal(1,writes);await Assertions.Expect(page.GetByRole(AriaRole.Button,new(){Name="Prepare reviewed completeness",Exact=true})).ToBeDisabledAsync();
    // Start the real owned background worker only after the interrupted request is reconciled.
    await host.StartGeneralWorkerAsync(); await WaitBridge(host);await page.GetByRole(AriaRole.Button,new(){Name="Refresh completeness",Exact=true}).ClickAsync();Guid bridge;
    await using(var db=host.CreateDbContext()){bridge=await db.GeneralLedgerCompletenessBridges.Select(x=>x.Id).SingleAsync();Assert.Single(await db.DurableOperations.ToListAsync());}
    await page.GetByRole(AriaRole.Button,new(){Name=$"Inspect completeness bridge {bridge:D}",Exact=true}).ClickAsync();await Assertions.Expect(page.GetByRole(AriaRole.Alert)).ToContainTextAsync("preparer");
    var reviewerOrigin=await host.StartApiForIdentityAsync(host.Fixture.Reviewer,new Dictionary<string,string>{["AngularUi__Enabled"]="true"});await using var reviewerContext=await browser.NewContextAsync();var reviewPage=await reviewerContext.NewPageAsync();reviewPage.PageError+=(_,e)=>errors.Add(e);
    await reviewPage.GotoAsync(reviewerOrigin+"/auth/sign-in?returnUrl="+Uri.EscapeDataString(Route(p.BatchId)));await reviewPage.GetByRole(AriaRole.Button,new(){Name=$"Inspect completeness bridge {bridge:D}",Exact=true}).ClickAsync();
    await Assertions.Expect(reviewPage.GetByRole(AriaRole.Region,new(){Name="Account-exact completeness residuals",Exact=true})).ToContainTextAsync("100.123456");await reviewPage.GetByLabel(Assent,new(){Exact=true}).CheckAsync();await reviewPage.GetByRole(AriaRole.Button,new(){Name="Record independent completeness decision",Exact=true}).ClickAsync();await Assertions.Expect(reviewPage.Locator("body")).ToContainTextAsync("APPROVED");await Assertions.Expect(reviewPage.GetByRole(AriaRole.Button,new(){Name="Record independent completeness decision",Exact=true})).ToBeDisabledAsync();
    await reviewPage.SetViewportSizeAsync(390,844);Assert.True(await reviewPage.EvaluateAsync<bool>("() => document.documentElement.scrollWidth <= window.innerWidth + 1"));
    await using(var db=host.CreateDbContext()){var proof=await db.GeneralLedgerCompletenessBridges.SingleAsync();Assert.Equal("APPROVED",proof.Status);Assert.Equal(host.Fixture.Reviewer.Id,proof.ReviewedByUserId);Assert.Empty(await db.SourceAcceptanceDecisions.ToListAsync());await db.Users.Where(x=>x.Id==host.Fixture.Reviewer.Id).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.SessionEpoch,x=>x.SessionEpoch+1));}
    await Assertions.Expect(reviewPage.GetByRole(AriaRole.Heading,new(){Name="Access unavailable",Exact=true})).ToBeVisibleAsync(new(){Timeout=15000});Assert.DoesNotContain("Synthetic browser completeness evidence",await reviewPage.Locator("body").InnerTextAsync());Assert.Empty(errors);
  }
  [Fact]
  [Trait("CaseId","ANGULAR-GL-COMPLETENESS-GATES")]
  public async Task MissingOpeningEvidence_NativeDraftProtection_StaleAssentAndIndependentRejection()
  {
    await using var host=await OwnedHost.StartAsync(startWorker:false,caseId:"ANGULAR-GL-COMPLETENESS-GATES");var p=await Seed(host,missingOpening:true);
    var origin=await host.StartApiForIdentityAsync(host.Fixture.Staff,new Dictionary<string,string>{["AngularUi__Enabled"]="true"});using var pw=await Playwright.CreateAsync();await using var browser=await PlaywrightBrowser.LaunchAsync(pw);var page=await browser.NewPageAsync();
    await page.GotoAsync(origin+"/auth/sign-in?returnUrl="+Uri.EscapeDataString(Route(p.BatchId)));await page.GetByLabel("Closing trial balance",new(){Exact=true}).SelectOptionAsync(p.ClosingId.ToString("D"));await page.GetByRole(AriaRole.Button,new(){Name="Review completeness source pair",Exact=true}).ClickAsync();await Assertions.Expect(page.Locator("body")).ToContainTextAsync("Unknown opening is never zero");
    await page.GetByLabel("Completeness evidence reference",new(){Exact=true}).FillAsync("Unsubmitted completeness draft");await page.GetByRole(AriaRole.Link,new(){Name="Back to general ledger inspection",Exact=true}).ClickAsync();await Assertions.Expect(page.GetByRole(AriaRole.Dialog)).ToBeVisibleAsync();await page.GetByRole(AriaRole.Button,new(){Name="Keep editing",Exact=true}).ClickAsync();
    await page.GetByLabel(Assent,new(){Exact=true}).CheckAsync();await using(var db=host.CreateDbContext())await db.ClientSafetyStates.Where(x=>x.Id==host.Fixture.ClientId).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.InputGeneration,x=>x.InputGeneration+1));await page.GetByRole(AriaRole.Button,new(){Name="Prepare reviewed completeness",Exact=true}).ClickAsync();await Assertions.Expect(page.GetByRole(AriaRole.Status)).ToContainTextAsync("changed");
    var refreshed=await page.RunAndWaitForResponseAsync(()=>page.GetByRole(AriaRole.Button,new(){Name="Refresh completeness",Exact=true}).ClickAsync(),r=>r.Url.Contains("/completeness?page=1&openingPage=1",StringComparison.Ordinal));Assert.Equal(200,refreshed.Status);await Assertions.Expect(page.GetByRole(AriaRole.Button,new(){Name="Refresh completeness",Exact=true})).ToBeEnabledAsync();await page.GetByLabel("Opening trial balance",new(){Exact=true}).SelectOptionAsync(p.OpeningId.ToString("D"));var planResponse=await page.RunAndWaitForResponseAsync(()=>page.GetByRole(AriaRole.Button,new(){Name="Review completeness source pair",Exact=true}).ClickAsync(),r=>r.Url.Contains("/completeness/plan?",StringComparison.Ordinal));Assert.Contains("openingId="+p.OpeningId.ToString("D"),planResponse.Url);await page.GetByLabel(Assent,new(){Exact=true}).CheckAsync();await page.GetByRole(AriaRole.Button,new(){Name="Prepare reviewed completeness",Exact=true}).ClickAsync();await Assertions.Expect(page.GetByRole(AriaRole.Status)).ToContainTextAsync("queued");await host.StartGeneralWorkerAsync();await WaitBridge(host);Guid bridge;await using(var db=host.CreateDbContext())bridge=await db.GeneralLedgerCompletenessBridges.Select(x=>x.Id).SingleAsync();
    var ro=await host.StartApiForIdentityAsync(host.Fixture.Reviewer,new Dictionary<string,string>{["AngularUi__Enabled"]="true"});await using var context=await browser.NewContextAsync();var rp=await context.NewPageAsync();await rp.GotoAsync(ro+"/auth/sign-in?returnUrl="+Uri.EscapeDataString(Route(p.BatchId)));await rp.GetByRole(AriaRole.Button,new(){Name=$"Inspect completeness bridge {bridge:D}",Exact=true}).ClickAsync();await Assertions.Expect(rp.Locator("body")).ToContainTextAsync("OPENING_ACCOUNT_COVERAGE_MISSING");await Assertions.Expect(rp.GetByRole(AriaRole.Region,new(){Name="Account-exact completeness residuals",Exact=true})).ToContainTextAsync("Unknown");await rp.GetByLabel(Assent,new(){Exact=true}).CheckAsync();await Assertions.Expect(rp.GetByRole(AriaRole.Button,new(){Name="Record independent completeness decision",Exact=true})).ToBeDisabledAsync();await rp.GetByLabel("Completeness review decision",new(){Exact=true}).SelectOptionAsync("reject");await Assertions.Expect(rp.GetByLabel(Assent,new(){Exact=true})).Not.ToBeCheckedAsync();await rp.GetByLabel(Assent,new(){Exact=true}).CheckAsync();await rp.GetByRole(AriaRole.Button,new(){Name="Record independent completeness decision",Exact=true}).ClickAsync();await Assertions.Expect(rp.Locator("body")).ToContainTextAsync("REJECTED");
  }
  private static async Task WaitBridge(OwnedHost host){var until=DateTimeOffset.UtcNow.AddSeconds(25);while(DateTimeOffset.UtcNow<until){await using var db=host.CreateDbContext();if(await db.GeneralLedgerCompletenessBridges.AnyAsync())return;await Task.Delay(150);}Assert.Fail("The owned background worker did not retain a completeness bridge.");}
  private const string Assent="I reviewed this exact source pair or retained proof and the requested completeness action.";
  private static string Route(Guid id)=>$"/ui/app/accounting/gl-sources/{id}/completeness";
  private static async Task<GeneralLedgerCompletenessSeed.Pair> Seed(OwnedHost host,bool missingOpening=false){await using var db=host.CreateDbContext();return await GeneralLedgerCompletenessSeed.SeedAsync(db,host.Fixture,missingOpening,missingOpening?4:2);}
}
