using System.Collections.Generic;
using System.Linq;

namespace AuditSphereOps.Application.Audit;

public sealed record AuditProgramCatalogItem(
  string SourceProcedureId, int SectionNumber, string SectionTitle, int Ordinal, string SourceWording);

/// <summary>Controlled source manifest for the 20-section audit working-process document.</summary>
public static class AuditProgramCatalog
{
  public const string ProgramCode = "AUDIT-WORKING-PROCESS";
  public const string SourceHash = "034d3b5023f5b498f0953ef6fea2af8439d72cc107075bd3336e53405091d987";

  public static IReadOnlyList<AuditProgramCatalogItem> Items { get; } =
  [
    new("AWP-01-01", 1, "Planning & Risk Assessment", 1, "Obtain company registration documents and basic company information."),
    new("AWP-01-02", 1, "Planning & Risk Assessment", 2, "Obtain prior-year audited financial statements and audit report."),
    new("AWP-01-03", 1, "Planning & Risk Assessment", 3, "Obtain current-year Trial Balance and draft financial statements."),
    new("AWP-01-04", 1, "Planning & Risk Assessment", 4, "Agree opening balances with prior-year audited balances."),
    new("AWP-01-05", 1, "Planning & Risk Assessment", 5, "Understand the nature of business, major revenue streams and accounting system."),
    new("AWP-01-06", 1, "Planning & Risk Assessment", 6, "Identify significant account balances and transaction classes."),
    new("AWP-01-07", 1, "Planning & Risk Assessment", 7, "Identify significant audit risks, fraud risks and areas involving management judgement."),
    new("AWP-01-08", 1, "Planning & Risk Assessment", 8, "Determine materiality and performance materiality."),
    new("AWP-01-09", 1, "Planning & Risk Assessment", 9, "Prepare the audit strategy and audit program."),
    new("AWP-02-01", 2, "Cash & Bank", 1, "Obtain bank reconciliation for all bank accounts at year-end."),
    new("AWP-02-02", 2, "Cash & Bank", 2, "Agree bank ledger balances with the Trial Balance."),
    new("AWP-02-03", 2, "Cash & Bank", 3, "Agree bank reconciliation balances with year-end bank statements."),
    new("AWP-02-04", 2, "Cash & Bank", 4, "Obtain direct bank confirmations and reconcile confirmed balances."),
    new("AWP-02-05", 2, "Cash & Bank", 5, "Check outstanding cheques, deposits and other reconciling items."),
    new("AWP-02-06", 2, "Cash & Bank", 6, "Investigate old or unusual outstanding items."),
    new("AWP-02-07", 2, "Cash & Bank", 7, "Test selected bank transactions to supporting documents."),
    new("AWP-02-08", 2, "Cash & Bank", 8, "Review subsequent bank statements for unusual transactions."),
    new("AWP-03-01", 3, "Trade Receivables", 1, "Obtain the year-end receivable ageing report."),
    new("AWP-03-02", 3, "Trade Receivables", 2, "Agree total receivables and ageing to the GL/TB."),
    new("AWP-03-03", 3, "Trade Receivables", 3, "Review significant and overdue customer balances."),
    new("AWP-03-04", 3, "Trade Receivables", 4, "Send customer balance confirmations and investigate differences."),
    new("AWP-03-05", 3, "Trade Receivables", 5, "Perform alternative procedures for non-confirmed balances."),
    new("AWP-03-06", 3, "Trade Receivables", 6, "Test selected sales invoices to delivery documents and ledger."),
    new("AWP-03-07", 3, "Trade Receivables", 7, "Check subsequent customer collections through bank statements."),
    new("AWP-03-08", 3, "Trade Receivables", 8, "Perform/recalculate ECL and assess adequacy of provision."),
    new("AWP-03-09", 3, "Trade Receivables", 9, "Test sales and receivable cut-off around year-end."),
    new("AWP-04-01", 4, "Inventory", 1, "Obtain the year-end inventory listing and agree it to the GL."),
    new("AWP-04-02", 4, "Inventory", 2, "Attend/observe physical inventory count where applicable."),
    new("AWP-04-03", 4, "Inventory", 3, "Perform auditor test counts and reconcile differences."),
    new("AWP-04-04", 4, "Inventory", 4, "Check inventory quantities against count sheets/final listing."),
    new("AWP-04-05", 4, "Inventory", 5, "Test inventory costs to purchase invoices or supporting records."),
    new("AWP-04-06", 4, "Inventory", 6, "Review slow-moving, damaged and obsolete inventory."),
    new("AWP-04-07", 4, "Inventory", 7, "Compare cost with NRV where applicable."),
    new("AWP-04-08", 4, "Inventory", 8, "Test purchases and goods received around year-end for cut-off."),
    new("AWP-05-01", 5, "Revenue / Sales", 1, "Obtain sales listing and reconcile total revenue to GL/TB."),
    new("AWP-05-02", 5, "Revenue / Sales", 2, "Perform analytical review of monthly and annual sales."),
    new("AWP-05-03", 5, "Revenue / Sales", 3, "Select sales samples based on value and risk."),
    new("AWP-05-04", 5, "Revenue / Sales", 4, "Check invoices to customer orders/delivery documents."),
    new("AWP-05-05", 5, "Revenue / Sales", 5, "Verify quantity, price, calculation and accounting entry."),
    new("AWP-05-06", 5, "Revenue / Sales", 6, "Check selected subsequent receipts where relevant."),
    new("AWP-05-07", 5, "Revenue / Sales", 7, "Review significant credit notes after year-end."),
    new("AWP-05-08", 5, "Revenue / Sales", 8, "Perform revenue cut-off testing before and after year-end."),
    new("AWP-06-01", 6, "Purchases & Trade Payables", 1, "Obtain supplier ageing and reconcile it to the GL/TB."),
    new("AWP-06-02", 6, "Purchases & Trade Payables", 2, "Review significant, old and unusual supplier balances."),
    new("AWP-06-03", 6, "Purchases & Trade Payables", 3, "Obtain supplier confirmations and investigate differences."),
    new("AWP-06-04", 6, "Purchases & Trade Payables", 4, "Compare supplier statements with the company's payable ledger."),
    new("AWP-06-05", 6, "Purchases & Trade Payables", 5, "Test selected purchases to invoices, GRNs and purchase orders."),
    new("AWP-06-06", 6, "Purchases & Trade Payables", 6, "Check subsequent payments to identify outstanding liabilities."),
    new("AWP-06-07", 6, "Purchases & Trade Payables", 7, "Perform search for unrecorded liabilities."),
    new("AWP-06-08", 6, "Purchases & Trade Payables", 8, "Test purchase and payable cut-off around year-end."),
    new("AWP-07-01", 7, "Fixed Assets", 1, "Obtain the fixed asset register and reconcile it to the GL."),
    new("AWP-07-02", 7, "Fixed Assets", 2, "Agree opening balances with prior-year audited balances."),
    new("AWP-07-03", 7, "Fixed Assets", 3, "Test additions to invoices, payment records and approvals."),
    new("AWP-07-04", 7, "Fixed Assets", 4, "Determine whether expenditure is correctly capitalized."),
    new("AWP-07-05", 7, "Fixed Assets", 5, "Physically verify significant additions/assets where appropriate."),
    new("AWP-07-06", 7, "Fixed Assets", 6, "Test disposals to disposal documents and sale proceeds."),
    new("AWP-07-07", 7, "Fixed Assets", 7, "Recalculate depreciation for selected assets."),
    new("AWP-07-08", 7, "Fixed Assets", 8, "Check useful lives and depreciation method."),
    new("AWP-07-09", 7, "Fixed Assets", 9, "Review assets for impairment, damage or obsolescence."),
    new("AWP-08-01", 8, "Expenses", 1, "Obtain detailed expense listing and reconcile to GL/TB."),
    new("AWP-08-02", 8, "Expenses", 2, "Perform analytical review against prior year and budget where available."),
    new("AWP-08-03", 8, "Expenses", 3, "Identify significant and unusual expense movements."),
    new("AWP-08-04", 8, "Expenses", 4, "Select samples based on value and risk."),
    new("AWP-08-05", 8, "Expenses", 5, "Check invoices and supporting documentation."),
    new("AWP-08-06", 8, "Expenses", 6, "Check management approval and payment evidence."),
    new("AWP-08-07", 8, "Expenses", 7, "Verify correct accounting classification."),
    new("AWP-08-08", 8, "Expenses", 8, "Check whether any capital expenditure has been incorrectly expensed."),
    new("AWP-08-09", 8, "Expenses", 9, "Perform expense cut-off testing."),
    new("AWP-09-01", 9, "Payroll", 1, "Obtain annual/monthly payroll summary and reconcile to GL."),
    new("AWP-09-02", 9, "Payroll", 2, "Select employees for detailed testing."),
    new("AWP-09-03", 9, "Payroll", 3, "Check employment contracts and salary details."),
    new("AWP-09-04", 9, "Payroll", 4, "Recalculate gross salary, allowances and deductions."),
    new("AWP-09-05", 9, "Payroll", 5, "Agree selected salary payments to bank statements."),
    new("AWP-09-06", 9, "Payroll", 6, "Test new employees and supporting employment documents."),
    new("AWP-09-07", 9, "Payroll", 7, "Check terminated employees and final payments."),
    new("AWP-09-08", 9, "Payroll", 8, "Review unusual changes in payroll or employee numbers."),
    new("AWP-10-01", 10, "Loans & Borrowings", 1, "Obtain loan/borrowing schedule and agree it to GL."),
    new("AWP-10-02", 10, "Loans & Borrowings", 2, "Agree opening balances to prior-year financial statements."),
    new("AWP-10-03", 10, "Loans & Borrowings", 3, "Obtain bank/financier confirmation."),
    new("AWP-10-04", 10, "Loans & Borrowings", 4, "Check new loans against agreements and bank receipts."),
    new("AWP-10-05", 10, "Loans & Borrowings", 5, "Check repayments against bank statements."),
    new("AWP-10-06", 10, "Loans & Borrowings", 6, "Recalculate interest expense and accrued interest."),
    new("AWP-10-07", 10, "Loans & Borrowings", 7, "Check current and non-current classification."),
    new("AWP-10-08", 10, "Loans & Borrowings", 8, "Review loan terms, security and covenant requirements where applicable."),
    new("AWP-10-09", 10, "Loans & Borrowings", 9, "Check subsequent repayments."),
    new("AWP-11-01", 11, "Equity / Share Capital", 1, "Obtain share capital and equity movement schedule."),
    new("AWP-11-02", 11, "Equity / Share Capital", 2, "Agree opening balances with prior-year audited FS."),
    new("AWP-11-03", 11, "Equity / Share Capital", 3, "Agree share capital to company/CR records."),
    new("AWP-11-04", 11, "Equity / Share Capital", 4, "Check additions, transfers or changes in shareholding."),
    new("AWP-11-05", 11, "Equity / Share Capital", 5, "Check dividend declarations and payments."),
    new("AWP-11-06", 11, "Equity / Share Capital", 6, "Reconcile retained earnings movement with profit/loss."),
    new("AWP-11-07", 11, "Equity / Share Capital", 7, "Agree closing equity balances to financial statements."),
    new("AWP-12-01", 12, "Related Parties", 1, "Obtain management's related-party listing."),
    new("AWP-12-02", 12, "Related Parties", 2, "Check directors, shareholders and key management records."),
    new("AWP-12-03", 12, "Related Parties", 3, "Review related-party transactions during the year."),
    new("AWP-12-04", 12, "Related Parties", 4, "Review significant related-party balances."),
    new("AWP-12-05", 12, "Related Parties", 5, "Confirm significant balances where appropriate."),
    new("AWP-12-06", 12, "Related Parties", 6, "Check whether transactions are properly recorded."),
    new("AWP-12-07", 12, "Related Parties", 7, "Verify required related-party disclosures in the financial statements."),
    new("AWP-13-01", 13, "Tax & Statutory Liabilities", 1, "Obtain tax returns and tax computations."),
    new("AWP-13-02", 13, "Tax & Statutory Liabilities", 2, "Reconcile tax balances with the GL/TB."),
    new("AWP-13-03", 13, "Tax & Statutory Liabilities", 3, "Check tax payments against bank statements."),
    new("AWP-13-04", 13, "Tax & Statutory Liabilities", 4, "Review outstanding tax liabilities and penalties."),
    new("AWP-13-05", 13, "Tax & Statutory Liabilities", 5, "Review correspondence with tax authorities."),
    new("AWP-13-06", 13, "Tax & Statutory Liabilities", 6, "Check tax provisions and current-year tax expense."),
    new("AWP-13-07", 13, "Tax & Statutory Liabilities", 7, "Check relevant tax disclosures in the financial statements."),
    new("AWP-14-01", 14, "Journal Entries & Fraud", 1, "Obtain journal entry listing for the audit period."),
    new("AWP-14-02", 14, "Journal Entries & Fraud", 2, "Identify unusual, manual and high-value journal entries."),
    new("AWP-14-03", 14, "Journal Entries & Fraud", 3, "Focus on journals posted close to year-end."),
    new("AWP-14-04", 14, "Journal Entries & Fraud", 4, "Select samples based on risk."),
    new("AWP-14-05", 14, "Journal Entries & Fraud", 5, "Check supporting documents and authorization."),
    new("AWP-14-06", 14, "Journal Entries & Fraud", 6, "Review unusual journals affecting revenue, expenses or reserves."),
    new("AWP-14-07", 14, "Journal Entries & Fraud", 7, "Check reversed or unusual post-year-end journals."),
    new("AWP-14-08", 14, "Journal Entries & Fraud", 8, "Document any fraud indicators or management override concerns."),
    new("AWP-15-01", 15, "Analytical Review", 1, "Compare current-year results with prior year."),
    new("AWP-15-02", 15, "Analytical Review", 2, "Analyse monthly revenue and expense trends."),
    new("AWP-15-03", 15, "Analytical Review", 3, "Compare gross profit and net profit margins."),
    new("AWP-15-04", 15, "Analytical Review", 4, "Analyse significant movements in major accounts."),
    new("AWP-15-05", 15, "Analytical Review", 5, "Calculate relevant ratios and key performance indicators."),
    new("AWP-15-06", 15, "Analytical Review", 6, "Review receivable, payable and inventory days where applicable."),
    new("AWP-15-07", 15, "Analytical Review", 7, "Investigate significant or unexpected fluctuations."),
    new("AWP-15-08", 15, "Analytical Review", 8, "Obtain management explanations and supporting evidence."),
    new("AWP-16-01", 16, "Going Concern", 1, "Obtain management's going-concern assessment."),
    new("AWP-16-02", 16, "Going Concern", 2, "Review current financial position and working capital."),
    new("AWP-16-03", 16, "Going Concern", 3, "Review cash flow forecasts."),
    new("AWP-16-04", 16, "Going Concern", 4, "Check expected cash inflows and major payments."),
    new("AWP-16-05", 16, "Going Concern", 5, "Review loan repayments and financing facilities."),
    new("AWP-16-06", 16, "Going Concern", 6, "Review losses, negative cash flows and overdue liabilities."),
    new("AWP-16-07", 16, "Going Concern", 7, "Assess significant assumptions used in forecasts."),
    new("AWP-16-08", 16, "Going Concern", 8, "Consider subsequent trading performance."),
    new("AWP-16-09", 16, "Going Concern", 9, "Document the auditor's conclusion."),
    new("AWP-17-01", 17, "Subsequent Events", 1, "Review post-year-end bank statements and transactions."),
    new("AWP-17-02", 17, "Subsequent Events", 2, "Review significant sales, purchases and payments after year-end."),
    new("AWP-17-03", 17, "Subsequent Events", 3, "Review board/management meeting minutes."),
    new("AWP-17-04", 17, "Subsequent Events", 4, "Check new loans, investments or major asset purchases."),
    new("AWP-17-05", 17, "Subsequent Events", 5, "Review litigation and significant legal developments."),
    new("AWP-17-06", 17, "Subsequent Events", 6, "Discuss significant events with management."),
    new("AWP-17-07", 17, "Subsequent Events", 7, "Determine whether events require adjustment or disclosure."),
    new("AWP-17-08", 17, "Subsequent Events", 8, "Ensure relevant events are reflected in the financial statements."),
    new("AWP-18-01", 18, "Financial Statements & Disclosures", 1, "Agree final financial statements to the audited Trial Balance."),
    new("AWP-18-02", 18, "Financial Statements & Disclosures", 2, "Check statement of financial position and profit/loss."),
    new("AWP-18-03", 18, "Financial Statements & Disclosures", 3, "Check cash flow statement and statement of changes in equity."),
    new("AWP-18-04", 18, "Financial Statements & Disclosures", 4, "Review accounting policies and significant estimates."),
    new("AWP-18-05", 18, "Financial Statements & Disclosures", 5, "Check comparative figures with prior-year audited FS."),
    new("AWP-18-06", 18, "Financial Statements & Disclosures", 6, "Check note disclosures and supporting schedules."),
    new("AWP-18-07", 18, "Financial Statements & Disclosures", 7, "Check related-party, tax and going-concern disclosures."),
    new("AWP-18-08", 18, "Financial Statements & Disclosures", 8, "Check subsequent-event disclosures."),
    new("AWP-18-09", 18, "Financial Statements & Disclosures", 9, "Perform final financial statement consistency and mathematical review."),
    new("AWP-19-01", 19, "Audit Differences & Adjustments", 1, "Record all identified audit differences."),
    new("AWP-19-02", 19, "Audit Differences & Adjustments", 2, "Obtain management's response to proposed adjustments."),
    new("AWP-19-03", 19, "Audit Differences & Adjustments", 3, "Recalculate the financial statement impact of each difference."),
    new("AWP-19-04", 19, "Audit Differences & Adjustments", 4, "Update the adjusted and unadjusted misstatement schedule."),
    new("AWP-19-05", 19, "Audit Differences & Adjustments", 5, "Compare total unadjusted differences with materiality."),
    new("AWP-19-06", 19, "Audit Differences & Adjustments", 6, "Assess whether remaining differences affect the audit conclusion."),
    new("AWP-19-07", 19, "Audit Differences & Adjustments", 7, "Ensure all agreed adjustments are posted and reflected in the final TB."),
    new("AWP-20-01", 20, "Final Completion & Audit Report", 1, "Ensure all audit sections are completed and cross-referenced."),
    new("AWP-20-02", 20, "Final Completion & Audit Report", 2, "Ensure all review points have been cleared."),
    new("AWP-20-03", 20, "Final Completion & Audit Report", 3, "Confirm all significant risks have been addressed."),
    new("AWP-20-04", 20, "Final Completion & Audit Report", 4, "Review audit differences and final materiality assessment."),
    new("AWP-20-05", 20, "Final Completion & Audit Report", 5, "Complete going-concern and subsequent-event procedures."),
    new("AWP-20-06", 20, "Final Completion & Audit Report", 6, "Complete financial statement disclosure checklist."),
    new("AWP-20-07", 20, "Final Completion & Audit Report", 7, "Obtain signed management representation letter."),
    new("AWP-20-08", 20, "Final Completion & Audit Report", 8, "Perform final analytical review."),
    new("AWP-20-09", 20, "Final Completion & Audit Report", 9, "Complete senior/manager/partner review."),
    new("AWP-20-10", 20, "Final Completion & Audit Report", 10, "Finalize the auditor's report and signed financial statements."),
  ];

  public static bool IsComplete => Items.Count == 165 &&
    Items.Select(x => x.SourceProcedureId).Distinct(StringComparer.Ordinal).Count() == 165 &&
    Items.Select(x => x.SectionNumber).Distinct().Count() == 20;
}
