// <auto-generated />
using System;
using AuditSphereOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditSphereOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditSphereDbContext))]
    [Migration("20260917075145_TrialBalanceValidation")]
    partial class TrialBalanceValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditSphereOps.Domain.Acceptance.AcceptanceDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<Guid?>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<Guid>("PracticeClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_client_id");

                    b.Property<string>("ServiceRoute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_route");

                    b.HasKey("Id");

                    b.ToTable("acceptance_decisions");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Acceptance.EvaluationResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("AnsweredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("answered_by_user_id");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("PracticeClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_client_id");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id");

                    b.ToTable("evaluation_responses");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.AdjustmentJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseDatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_dataset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journal_number");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "EngagementId", "BaseDatasetId", "JournalNumber")
                        .IsUnique();

                    b.ToTable("adjustment_journals");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.AdjustmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("debit");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.HasKey("Id");

                    b.ToTable("adjustment_lines");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.FinancialPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdjustedDatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjusted_dataset_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("financial_packages");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.MappingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("MappingCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapping_code");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SourcePattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_pattern");

                    b.HasKey("Id");

                    b.ToTable("mapping_rules");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.TrialBalanceDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Balanced")
                        .HasColumnType("boolean")
                        .HasColumnName("balanced");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<decimal>("ControlTotal")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("control_total");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<Guid>("ImportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by_user_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256_hex");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_kind");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.ToTable("trial_balance_datasets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tb_validation_status", "validation_status IN ('Pending', 'Accepted', 'Rejected') AND (validation_status <> 'Accepted' OR (balanced AND control_total = 0))");
                        });
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Accounting.TrialBalanceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<string>("MappingCode")
                        .HasColumnType("text")
                        .HasColumnName("mapping_code");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("trial_balance_rows");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Audit.AuditProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("audit_procedures");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Audit.AuditRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assertion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assertion");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.ToTable("audit_risks");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Audit.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("findings");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Audit.Workpaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("workpapers");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Completion.Archive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("archives");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Completion.DurableOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_digest");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("durable_operations");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Completion.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<bool>("ExternalCheckpoint")
                        .HasColumnType("boolean")
                        .HasColumnName("external_checkpoint");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest_digest");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<long>("PackageRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("package_revision");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid>("ReleasedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("releases");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Documents.DocumentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drive_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.HasKey("Id");

                    b.ToTable("document_references");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Documents.DocumentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteCount")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_count");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("captured_by");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("DocumentReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_reference_id");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drive_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_id");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256_hex");

                    b.Property<string>("VersionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentReferenceId", "VersionId")
                        .IsUnique();

                    b.ToTable("document_snapshots");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Engagements.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_end");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_start");

                    b.Property<Guid>("PracticeClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_client_id");

                    b.Property<bool>("ProfessionalWorkBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("professional_work_blocked");

                    b.Property<string>("ServiceProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_profile_id");

                    b.Property<string>("ServiceRoute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_route");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("engagements");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Engagements.EngagementHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("HoldKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hold_kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<bool>("Released")
                        .HasColumnType("boolean")
                        .HasColumnName("released");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("Id");

                    b.ToTable("engagement_holds");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("Id");

                    b.ToTable("allocations");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("PracticeClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_client_id");

                    b.HasKey("Id");

                    b.ToTable("billing_accounts");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.BudgetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("hours");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("budget_versions");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.ClientContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("PracticeClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_client_id");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("primary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("client_contacts");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.FirmAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalSide")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normal_side");

                    b.Property<bool>("PostingAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("posting_allowed");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "Code")
                        .IsUnique();

                    b.ToTable("firm_accounts");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.FirmJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("JournalNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journal_number");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "SourceKind", "SourceKey")
                        .IsUnique();

                    b.ToTable("firm_journals");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.FirmJournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("debit");

                    b.Property<Guid>("FirmAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_account_id");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.HasKey("Id");

                    b.ToTable("firm_journal_lines");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.FirmPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "PeriodCode")
                        .IsUnique();

                    b.ToTable("firm_periods");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("tax");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.ToTable("invoice_lines");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("ServiceRoute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_route");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.ToTable("opportunities");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.PracticeClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("CommercialName")
                        .HasColumnType("text")
                        .HasColumnName("commercial_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "LegalName")
                        .IsUnique();

                    b.ToTable("practice_clients");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ServiceProfileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("proposals");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("hours");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("time_entries");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Practice.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("work_tasks");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Records.RecordState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artifact_kind");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<string>("LocalState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_state");

                    b.Property<string>("ObservedLabel")
                        .HasColumnType("text")
                        .HasColumnName("observed_label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("record_states");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Reviews.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("InputGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("input_generation");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manifest_digest");

                    b.Property<long>("PolicyGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("policy_generation");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<long>("TargetRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("target_revision");

                    b.HasKey("Id");

                    b.ToTable("approvals");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Reviews.ReviewPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Cleared")
                        .HasColumnType("boolean")
                        .HasColumnName("cleared");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by_user_id");

                    b.Property<bool>("Significant")
                        .HasColumnType("boolean")
                        .HasColumnName("significant");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_kind");

                    b.Property<long>("TargetRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("target_revision");

                    b.HasKey("Id");

                    b.ToTable("review_points");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Security.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<long>("SessionEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("session_epoch");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_kind");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AuditSphereOps.Domain.Security.RoleGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("EngagementId")
                        .HasColumnType("uuid")
                        .HasColumnName("engagement_id");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("role_grants");
                });
#pragma warning restore 612, 618
        }
    }
}
