import { engagementNavigationGuard } from './features/engagements/planning-navigation';
import { Routes } from '@angular/router';
import { clientGuard } from './core/client.guard';
import { unsavedChangesGuard } from './core/unsaved-changes';
import { staffGuard } from './core/staff.guard';
export const routes: Routes = [
  { path: 'setup/microsoft365', title: 'Initial administrator setup · AuditSphere',
    loadComponent: () => import('./features/admin/bootstrap').then(m => m.InstallationBootstrap) },
  { path: 'app/administration/microsoft365/tenant-connection', canActivate: [staffGuard], title: 'Microsoft tenant connection · AuditSphere',
    loadComponent: () => import('./features/admin/tenant').then(m => m.TenantConnection) },
  { path: 'app/administration/microsoft365', pathMatch: 'full', redirectTo: 'app/administration/microsoft365/tenant-connection' },
  { path: 'app/administration/users', canActivate: [staffGuard], title: 'Users & Access · AuditSphere',
    loadComponent: () => import('./features/admin/access').then(m => m.UserAccess) },
  { path: 'app/administration', pathMatch: 'full', canActivate: [staffGuard], title: 'Administration · AuditSphere',
    loadComponent: () => import('./features/admin/overview').then(m => m.AdministrationOverview) },
  { path: 'portal/accounting/journals/:id', canActivate: [clientGuard], canDeactivate: [unsavedChangesGuard], data: { client: true }, title: 'Journal management response · AuditSphere',
    loadComponent: () => import('./features/accounting/journal-management').then(m => m.JournalManagement) },
  { path: 'portal/accounting/packages/:id', canActivate: [clientGuard], title: 'Management review · AuditSphere',
    loadComponent: () => import('./features/portal/package').then(m => m.ClientFinancialPackage) },
  { path: 'portal/requests/:id', canActivate: [clientGuard], title: 'Document request · AuditSphere',
    loadComponent: () => import('./features/portal/request').then(m => m.ClientPbcRequest) },
  { path: 'portal', canActivate: [clientGuard], title: 'Client portal · AuditSphere',
    loadComponent: () => import('./features/portal/home').then(m => m.ClientPortalHome) },
  { path: 'app/consolidation', canActivate: [staffGuard], pathMatch: 'full', title: 'Group consolidation · AuditSphere',
    loadComponent: () => import('./features/consolidation/overview').then(m => m.ConsolidationOverview) },
  { path: 'app/consolidation/scopes/:id', canActivate: [staffGuard], title: 'Consolidation scope workspace · AuditSphere',
    loadComponent: () => import('./features/consolidation/scope-workspace').then(m => m.ConsolidationScopeWorkspace) },
  { path: 'app/consolidation/advanced/:id', canActivate: [staffGuard], title: 'Advanced consolidation · AuditSphere',
    loadComponent: () => import('./features/consolidation/advanced').then(m => m.AdvancedConsolidation) },
  { path: 'app/operations', canActivate: [staffGuard], title: 'Operations · AuditSphere',
    loadComponent: () => import('./features/admin/operations').then(m => m.Operations) },
  { path: 'app/administration/project-progress', canActivate: [staffGuard], title: 'Project task progress · AuditSphere',
    loadComponent: () => import('./features/admin/progress').then(m => m.ProjectProgress) },
  { path: 'app/overview', pathMatch: 'full', redirectTo: 'app' },
  { path: 'app/assessments/:id/decision', canActivate: [staffGuard], title: 'Client acceptance · AuditSphere',
    loadComponent: () => import('./features/acceptance/assessment-route').then(m => m.AssessmentRoute) },
  { path: 'app/assessments/:id', canActivate: [staffGuard], title: 'Client acceptance · AuditSphere',
    loadComponent: () => import('./features/acceptance/assessment-route').then(m => m.AssessmentRoute) },
  { path: 'app/audit/library', canActivate: [staffGuard], title: 'Audit program library · AuditSphere',
    loadComponent: () => import('./features/audit/library').then(m => m.AuditProgramLibrary) },
  { path: 'app/audit/populations/:id', canActivate: [staffGuard], title: 'Population · AuditSphere',
    loadComponent: () => import('./features/audit/records').then(m => m.PopulationRecord) },
  { path: 'app/audit/workpapers/:id', canActivate: [staffGuard], title: 'Workpaper · AuditSphere',
    loadComponent: () => import('./features/audit/workpaper').then(m => m.WorkpaperEditor) },
  { path: 'app/findings/:id', canActivate: [staffGuard], title: 'Finding · AuditSphere',
    loadComponent: () => import('./features/audit/records').then(m => m.FindingRecord) },
  { path: 'app/reviews/:id', canActivate: [staffGuard], title: 'Review point · AuditSphere',
    loadComponent: () => import('./features/audit/records').then(m => m.ReviewPointRecord) },
  { path: 'app/releases/:id', canActivate: [staffGuard], title: 'Release candidate · AuditSphere',
    loadComponent: () => import('./features/audit/records').then(m => m.ReleaseCandidate) },
  { path: 'app/records/archives/:id', canActivate: [staffGuard], title: 'Records archive · AuditSphere',
    loadComponent: () => import('./features/audit/records').then(m => m.ArchiveRecord) },
  { path: 'app/finance', canActivate: [staffGuard], pathMatch: 'full', title: 'Firm ledger · AuditSphere',
    loadComponent: () => import('./features/finance/ledger').then(m => m.FirmLedger) },
  { path: 'app/practice/invoices/:id', canActivate: [staffGuard], title: 'Invoice · AuditSphere',
    loadComponent: () => import('./features/finance/invoice').then(m => m.InvoiceDetail) },
  { path: 'app/accounting/currency-configuration', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'FX rates & policies · AuditSphere',
    loadComponent: () => import('./features/accounting/currency-configuration').then(m => m.CurrencyConfiguration) },
  { path: 'app/accounting/remeasurement', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Currency remeasurement · AuditSphere',
    loadComponent: () => import('./features/accounting/remeasurement').then(m => m.CurrencyRemeasurement) },
  { path: 'app/accounting/gl-sources/:id/completeness', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'General ledger completeness · AuditSphere',
    loadComponent: () => import('./features/accounting/gl-completeness').then(m => m.GeneralLedgerCompleteness) },
  { path: 'app/accounting/gl-sources/:id/acceptance', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], data: { sourceKind: 'GL' }, title: 'General ledger source acceptance · AuditSphere',
    loadComponent: () => import('./features/accounting/source-acceptance').then(m => m.SourceAcceptance) },
  { path: 'app/accounting/sources/:id/acceptance', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Source acceptance · AuditSphere',
    loadComponent: () => import('./features/accounting/source-acceptance').then(m => m.SourceAcceptance) },
  { path: 'app/accounting/sources/:id/journal-draft', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Prepare journal · AuditSphere',
    loadComponent: () => import('./features/accounting/journal-create').then(m => m.JournalCreate) },
  { path: 'app/accounting/evidence', canActivate: [staffGuard], title: 'Accounting evidence · AuditSphere',
    loadComponent: () => import('./features/accounting/evidence').then(m => m.AccountingEvidence) },
  { path: 'app/accounting/reconciliations/:id/prepare/:kind', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Prepare valuation · AuditSphere',
    loadComponent: () => import('./features/accounting/valuation-preparation').then(m => m.ValuationPreparation) },
  { path: 'app/accounting/reconciliations/:id', canActivate: [staffGuard], title: 'Reconciliation evidence · AuditSphere',
    loadComponent: () => import('./features/accounting/reconciliation').then(m => m.ReconciliationReview) },
  { path: 'app/accounting/evidence/:kind/:id', canActivate: [staffGuard], title: 'Analysis evidence · AuditSphere',
    loadComponent: () => import('./features/accounting/analysis-review').then(m => m.AnalysisReview) },
  { path: 'app/accounting/evidence/:kind/:id/actions', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Review accounting evidence · AuditSphere',
    loadComponent: () => import('./features/accounting/evidence-actions').then(m => m.EvidenceActions) },
  { path: 'app/accounting/rollforward', canActivate: [staffGuard], title: 'Period roll-forward · AuditSphere',
    loadComponent: () => import('./features/accounting/rollforward').then(m => m.PeriodRollforward) },
  { path: 'app/accounting/restatements', canActivate: [staffGuard], title: 'Period restatements · AuditSphere',
    loadComponent: () => import('./features/accounting/restatements').then(m => m.PeriodRestatements) },
  { path: 'app/accounting/packages/:id', canActivate: [staffGuard], title: 'Financial statement package · AuditSphere',
    loadComponent: () => import('./features/accounting/package').then(m => m.FinancialPackage) },
  { path: 'app/accounting/reviews', canActivate: [staffGuard], title: 'Package reviews · AuditSphere',
    loadComponent: () => import('./features/accounting/reviews').then(m => m.PackageReviews) },
  { path: 'app/accounting/mappings/:id/edit', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Prepare mapping version · AuditSphere',
    loadComponent: () => import('./features/accounting/mapping-draft').then(m => m.MappingDraft) },
  { path: 'app/accounting/mappings/:id/approval', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Independent mapping review · AuditSphere',
    loadComponent: () => import('./features/accounting/mapping-approval').then(m => m.MappingApproval) },
  { path: 'app/accounting/mappings/:id', canActivate: [staffGuard], title: 'Accounting mapping · AuditSphere',
    loadComponent: () => import('./features/accounting/mapping').then(m => m.MappingWorkbench) },
  { path: 'app/accounting/periods/:id', canActivate: [staffGuard], title: 'Accounting period · AuditSphere',
    loadComponent: () => import('./features/accounting/period').then(m => m.AccountingPeriodRecord) },
  { path: 'app/accounting/mappings', canActivate: [staffGuard], title: 'Mappings · AuditSphere', data: { mode: 'mappings' },
    loadComponent: () => import('./features/accounting/records').then(m => m.AccountingRecords) },
  { path: 'app/accounting/journals/:id/management', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Journal management evidence · AuditSphere',
    loadComponent: () => import('./features/accounting/journal-management').then(m => m.JournalManagement) },
  { path: 'app/accounting/journals/:id', canActivate: [staffGuard], title: 'Adjustment journal · AuditSphere',
    canDeactivate: [unsavedChangesGuard], loadComponent: () => import('./features/accounting/journal').then(m => m.AdjustmentJournal) },
  { path: 'app/accounting/journals', canActivate: [staffGuard], title: 'Adjustment journals · AuditSphere', data: { mode: 'journals' },
    loadComponent: () => import('./features/accounting/records').then(m => m.AccountingRecords) },
  { path: 'app/accounting/sources/:id/adjustment-plan', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], data: { action: 'CREATE' }, title: 'Prepare adjustment plan · AuditSphere',
    loadComponent: () => import('./features/accounting/plan-command').then(m => m.PlanCommand) },
  { path: 'app/accounting/adjustment-plans/:id/finalize', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], data: { action: 'FINALIZE' }, title: 'Finalize adjustment plan · AuditSphere',
    loadComponent: () => import('./features/accounting/plan-command').then(m => m.PlanCommand) },
  { path: 'app/accounting/adjustment-plans/:id', canActivate: [staffGuard], title: 'Adjustment plan eligibility · AuditSphere',
    loadComponent: () => import('./features/accounting/adjustment-plans').then(m => m.AdjustmentPlanReview) },
  { path: 'app/accounting/adjustment-plans', canActivate: [staffGuard], title: 'Adjustment plan review · AuditSphere',
    loadComponent: () => import('./features/accounting/adjustment-plans').then(m => m.AdjustmentPlanQueue) },
  { path: 'app/accounting/differences', canActivate: [staffGuard], title: 'Audit differences · AuditSphere', data: { mode: 'differences' },
    loadComponent: () => import('./features/accounting/records').then(m => m.AccountingRecords) },
  { path: 'app/engagements/:id/pbc', canActivate: [staffGuard], title: 'PBC requests · AuditSphere',
    loadComponent: () => import('./features/engagements/pbc').then(m => m.PbcInbox) },
  { path: 'app/engagements/:id/completion', canActivate: [staffGuard], title: 'Engagement completion · AuditSphere',
    loadComponent: () => import('./features/audit/completion').then(m => m.EngagementCompletion) },
  { path: 'app/completion/:id', canActivate: [staffGuard], title: 'Engagement completion · AuditSphere',
    loadComponent: () => import('./features/audit/completion').then(m => m.EngagementCompletion) },
  { path: 'app/engagements/:id/confirmations', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], runGuardsAndResolvers: 'paramsOrQueryParamsChange', title: 'Confirmations · AuditSphere',
    loadComponent: () => import('./features/audit/confirmations').then(m => m.Confirmations) },
  { path: 'app/engagements/:id/audit-fieldwork', canActivate: [staffGuard], title: 'Audit fieldwork · AuditSphere',
    loadComponent: () => import('./features/audit/fieldwork').then(m => m.AuditFieldwork) },
  { path: 'app/engagements/:id/audit-plan', canActivate: [staffGuard], title: 'Audit plan · AuditSphere',
    loadComponent: () => import('./features/audit/plan').then(m => m.AuditPlan) },
  { path: 'app/audit/plans/:id', canActivate: [staffGuard], title: 'Audit plan · AuditSphere',
    loadComponent: () => import('./features/audit/plan').then(m => m.AuditPlan) },
  { path: 'app/practice/time', canActivate: [staffGuard], title: 'Time & work records · AuditSphere',
    loadComponent: () => import('./features/practice/time').then(m => m.PracticeTime) },
  { path: 'app/engagements/:id/general-ledger/upload', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'General ledger upload · AuditSphere',
    loadComponent: () => import('./features/engagements/gl-upload').then(m => m.GeneralLedgerUpload) },
  { path: 'app/engagements/:id/general-ledger', canActivate: [staffGuard], title: 'General ledger · AuditSphere',
    loadComponent: () => import('./features/engagements/general-ledger').then(m => m.GeneralLedger) },
  { path: 'app/engagements/:id/tb-intake', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Trial balance intake · AuditSphere',
    loadComponent: () => import('./features/engagements/tb-intake').then(m => m.TrialBalanceIntake) },
  { path: 'app/practice/resources', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Resource planning · AuditSphere',
    loadComponent: () => import('./features/practice/resources').then(m => m.ResourcePlanning) },
  { path: 'app/engagements/:id/statements', canActivate: [staffGuard], title: 'Financial statements · AuditSphere',
    loadComponent: () => import('./features/engagements/statements').then(m => m.StatementDrillDown) },
  { path: 'app/practice/analytics', canActivate: [staffGuard], title: 'Practice analytics · AuditSphere',
    loadComponent: () => import('./features/practice/analytics').then(m => m.PracticeAnalytics) },
  { path: 'app/library/:id', canActivate: [staffGuard], title: 'Technical library · AuditSphere',
    loadComponent: () => import('./features/library/library').then(m => m.TechnicalLibrary) },
  { path: 'app/library', canActivate: [staffGuard], title: 'Technical library · AuditSphere',
    loadComponent: () => import('./features/library/library').then(m => m.TechnicalLibrary) },
  { path: 'app/finance/books', canActivate: [staffGuard], title: 'Firm books · AuditSphere',
    loadComponent: () => import('./features/finance/books').then(m => m.FirmBooks) },
  { path: 'app/accounting', canActivate: [staffGuard], title: 'Accounting · AuditSphere',
    loadComponent: () => import('./features/accounting/workspace').then(m => m.AccountingWorkspace) },
  {
    path: 'app/practice/commercial-settings',
    canActivate: [staffGuard],
    title: 'Commercial settings · AuditSphere',
    loadComponent: () => import('./features/commercial/settings').then((m) => m.CommercialSettings),
  },
  {
    path: 'app/practice/leads/:id',
    canActivate: [staffGuard],
    title: 'Opportunities · AuditSphere',
    loadComponent: () => import('./features/commercial/opportunities').then((m) => m.Opportunities),
  },
  {
    path: 'app/practice/proposals/:id/client-conversion',
    canActivate: [staffGuard],
    canDeactivate: [unsavedChangesGuard],
    title: 'Convert prospect · AuditSphere',
    loadComponent: () => import('./features/commercial/client-conversion').then(m => m.ClientConversion),
  },
  {
    path: 'app/practice/proposals/:id',
    canActivate: [staffGuard],
    title: 'Proposal · AuditSphere',
    loadComponent: () => import('./features/commercial/proposal').then((m) => m.ProposalDetail),
  },
  {
    path: 'app/practice/leads',
    canActivate: [staffGuard],
    title: 'Leads · AuditSphere',
    loadComponent: () => import('./features/commercial/leads').then((m) => m.Leads),
  },
  {
    path: 'app/clients/:id/assessment',
    canActivate: [staffGuard],
    canDeactivate: [unsavedChangesGuard],
    runGuardsAndResolvers: 'paramsOrQueryParamsChange',
    title: 'Acceptance · AuditSphere',
    loadComponent: () =>
      import('./features/acceptance/checklist').then((m) => m.AcceptanceChecklist),
  },
  { path: 'app/engagements/:id/activation', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard],
    title: 'Review activation · AuditSphere', loadComponent: () => import('./features/engagements/activation').then(m => m.EngagementActivationReview) },
  {
    path: 'app/engagements/:id',
    canActivate: [staffGuard],
    canDeactivate: [engagementNavigationGuard],
    runGuardsAndResolvers: 'paramsOrQueryParamsChange',
    title: 'Engagement · AuditSphere',
    loadComponent: () =>
      import('./features/engagements/engagement').then((m) => m.EngagementDetail),
  },
  { path: 'app/clients/:id/engagements/new', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard], title: 'Create blocked engagement · AuditSphere',
    loadComponent: () => import('./features/clients/engagement-create').then(m => m.EngagementCreate) },
  { path: 'app/clients/:id/contacts/new', canActivate: [staffGuard], canDeactivate: [unsavedChangesGuard],
    title: 'Add client contact · AuditSphere', loadComponent: () => import('./features/clients/contact-create').then(m => m.ContactCreate) },
  {
    path: 'app/clients/:id',
    canActivate: [staffGuard],
    title: 'Client profile · AuditSphere',
    loadComponent: () => import('./features/clients/client').then((m) => m.ClientDetail),
  },
  {
    path: 'app',
    canActivate: [staffGuard],
    title: 'Portfolio · AuditSphere',
    loadComponent: () => import('./features/portfolio/portfolio').then((m) => m.Portfolio),
  },
  { path: '', pathMatch: 'full', redirectTo: 'app' },
];
